
# This file is automatically generated, you probably don't want to edit this

progressBarOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "progressBarOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            doSomething = NULL, ...) {

            super$initialize(
                package="SimpleTests",
                name="progressBar",
                requiresData=FALSE,
                ...)

            private$..doSomething <- jmvcore::OptionAction$new(
                "doSomething",
                doSomething)

            self$.addOption(private$..doSomething)
        }),
    active = list(
        doSomething = function() private$..doSomething$value),
    private = list(
        ..doSomething = NA)
)

progressBarResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "progressBarResults",
    inherit = jmvcore::Group,
    active = list(
        progressBarHTML = function() private$.items[["progressBarHTML"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="progressBar")
            self$add(jmvcore::Html$new(
                options=options,
                name="progressBarHTML",
                title=" ",
                visible=TRUE))}))

progressBarBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "progressBarBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SimpleTests",
                name = "progressBar",
                version = c(1,0,0),
                options = options,
                results = progressBarResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' progressBar
#'
#' 
#' @param doSomething .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$progressBarHTML} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
progressBar <- function(
    doSomething) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("progressBar requires jmvcore to be installed (restart may be required)")


    options <- progressBarOptions$new(
        doSomething = doSomething)

    analysis <- progressBarClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

